language: node_js

cache:
  directories:
    - node_modules

node_js:
  - '9.11'

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

install:
  - npm install

script:
  - npm test

after_success:
  - npm run semantic-release
